# Generated by Django 5.2.3 on 2025-06-13 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.CharField(error_messages={'max_length': 'El texto debe tener un máximo de 10 caracteres'}, max_length=10, primary_key=True, serialize=False)),
                ('ape_nom', models.CharField(max_length=200)),
                ('fec_reg', models.DateField()),
                ('fec_sis', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
