# Generated by Django 5.2.3 on 2025-07-05 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_alter_venta_total_alter_ventadetalle_precio_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='fecha_reg',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='fecha_reg',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
